baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[blackfriday]
  plainIDAnchors = false

[languages]
  [languages.en]
    languageName = "English"
    title = "Isis Events 2020"
    subtitle = "Events on the Isis, Oxford"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = ""

    [languages.en.params.logo]
      logoText = "Isis Events 2020"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "races"
        name = "Races"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "recurring"
        name = "Recurring events"
        url = "/recurring"
      [[languages.en.menu.main]]
        identifier = "restrictions"
        name = "Recurring restrictions"
        url = "/restrictions"